config/routes.rb
Rails.application.routes.draw do
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
  get 'reset', to: 'games#reset'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require'open-uri'

class GamesController < ApplicationController

  def new
    @letters = (0...15).map { ('A'..'Z').to_a[rand(26)] }
  end

  def score
    session[:score] = 0 if session[:score].nil?
    @word = params[:word].upcase
    user = open("https://wagon-dictionary.herokuapp.com/#{params[:word]}").read
    result_api = JSON.parse(user)
    @exists = result_api["found"]
    @letters = JSON.parse params[:collected_input]
    @correct = true
    letters = @letters
    params[:word].upcase.split('').each { |letter| letters.include?(letter) ? letters.slice(letters.index(letter)) : @correct = false }
    @exists == true && @correct == true ? @score = @word.length : @score = 0
    session[:score] += @score
    @total_score = session[:score]
   end


  def reset
    reset_session
    redirect_to new_url
    session[:score] = 0
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div id="wrapper">
  <div id="container">
    <h1>The Longest Word!</h1>
  </div>
</div>
<h2><% @letters.each do |letter| %>
  <%=letter%>
    <% end %>
</h2>

<h3>What is the longest word you can find</h3>
<form action="/score" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input id="collected_input" name="collected_input" onchange="alert('Input collected!')" type="hidden" value="<%= @letters%>"/>
  <input class="form-control" type="text" name="word" placeholder="Your word">
  <input class= "btn btn-light mt-3" type="submit">
</form>

<p class="score">Your score: <%= session[:score] %> <p class="btn btn-light"><%= link_to "Reset score", reset_path %></p> </p>

app/views/games/score.html.erb
<h2><% if @correct == false %>
  <h1>Sorry... </h1>
  <%= "#{@word} cannot be built out of" %> <% @letters.each do |letter| %>
  <%=letter%>
    <% end %>
<% elsif @exists == false %>
  <%= "Sorry... #{@word} is not a valid english word." %>
  <% else %>
  <h1>Congratulation!</h1>
  <%= "#{@word} is a valid English word! You scored #{@score} points this round" %>
  <% end %>
</p>
<p>Your score: <%= @total_score %></p>
<p class="btn btn-light"><%= link_to "Try Again", new_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>